server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/registry/eureka/

zuul:
  prefix: /api
  ignored-services: "*"
  routes:
    crud:
      path: /crud/**
      service-id: crud
      strip-prefix: false
      custom-sensitive-headers: true
    payment:
      path: /payment/**
      service-id: payment
      strip-prefix: false
      custom-sensitive-headers: true
    auth:
      path: /auth/**
      service-id: auth
      strip-prefix: false
      custom-sensitive-headers: true
