
server:
  port: 8761
  servlet:
    context-path: /registry

spring:
  application:
    name: registry

eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaltZone: http://localhost:${server.port}/eureka/

